"""
BU YERDA SIZGA KERAKLI BO'LADIGAN TOKEN VA SHUNGA O'XSHAGAN MA'LUMOTLAR SAQLANADI
"""
TOKEN = '6532917338:AAEE4jiwp7UVVf5ihFhWz61-FU81DsaZ-4o'
PROVIDER_TOKEN = "Pul o'tkazmalari uchun bo'lgan TOKEN buni ham botfatherdan olsa bo'ladi, test versiyasini"
ADMINS = [1845796926, 1490953190]
# ADMINS = []

# DB_NAME = '''POSTGRES ISHLATGANDA BAZANI ISMINI SAQLASH UCHUN'''
# DB_HOST = '''POSTGRES ISHLATGANDA BAZANI HOSTINI SAQLASH UCHUN'''
# DB_PASSWORD = '''POSTGRES ISHLATGANDA BAZANI PAROLINI SAQLASH UCHUN'''
# DB_PORT = '''POSTGRES ISHLATGANDA BAZANI PORTINI SAQLASH UCHUN'''
# DB_USER = '''POSTGRES ISHLATGANDA BAZANI FOYDALANUVCHISINING ISMINI SAQLASH UCHUN'''


